jobs:
    include:
        - language: node_js
          node_js: 
            - "stable"
          cache:
            directories:
                - node_modules
          script:
            - yarn --cwd ./eloquent-elks-frontend install
            - yarn --cwd ./eloquent-elks-frontend test -- --coverage
            - yarn --cwd ./eloquent-elks-frontend run build
          after_script:
            - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn --cwd ./eloquent-elks-frontend coveralls     
        - language: java
          install: skip
          os: linux
          dist: trusty
          jdk: oraclejdk8
          script:
            - gradlew -p ./eloquent-elks-poi-api build
            - gradlew -p ./eloquent-elks-poi-api test
addons:
    sonarcloud:
        organization: "eloquent-elks"
        token: $eloquent_elks_travis_ci
script:
    - sonar-scanner