version: '3.8'
services:
    mongodb:
        image: mongo
        container_name: airbnb-database
        environment:
        - PUID=1000
        - PGID=1000
        volumes:
        - ./eloquent-elks-airbnb-db/mongodb/database:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
        build: ./eloquent-elks-airbnb-db/mongodb

    dbseed:
        build:
            context: ./eloquent-elks-airbnb-db/dbseed
            dockerfile: Dockerfile
        links:
            - mongodb