version: '3.8'
services:
    mongodb:
        image: mongo:latest
        container_name: airbnb-database
        environment:
        - PUID=1000
        - PGID=1000
        volumes:
        - ./eloquent-elks-airbnb-db/mongodb/database:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
        
    dbseed_airbnb:
        build:
            context: ./eloquent-elks-airbnb-db/dbseed
            dockerfile: Dockerfile
        links:
            - mongodb
        depends_on:
            - mongodb

    springboot-mongodb:
      image: springboot-mongodb:1.0
      container_name: springboot-mongodb
      ports:
        - 8080:8080
      links:
        - mongodb

            
    mongodb_poi:
        image: mongo
        volumes:
        - ./eloquent-elks-poi-db/mongodb/database:/data/db
        ports:
        - 27018:27017
        restart: unless-stopped
                
    dbseed_poi:
        build:
            context: ./eloquent-elks-poi-db/dbseed
            dockerfile: Dockerfile
        links:
            - mongodb_poi
        depends_on:
            - mongodb_poi
