swagger: "2.0"
info:
  version: 1.0.0
  title: eloquent-elks-poi-density-api
  description: API that computes the POI density of POIs of an attraction type.
basePath: /api/v1
tags:
  - name: Density
    description: Calculates densities

consumes:
  - application/json
produces:
  - application/json


paths:
  /poiDensity :
    get:
      tags:
        - Examples
      description: Get density of attraction by type.
      parameters:
        - in: query
          name: attractionType
          type: string
          required: true
          description: String name of attraction type for which to get the density
      responses:
        200:
          description: Returns density of selected attraction type

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
