swagger: "2.0"
info:
  version: 1.0.0
  title: eloquent-elks-poi-density-api
  description: API that computes the POI density of POIs of a certain type
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

paths:
  /poiDensity:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification